### ISSUE TITLE
Other signatures

### ISSUE THREAD

**Issue by georgelemon** [jiro4989/filetype#18]
Great library!

Other (must-have) signatures. Already made a PR for `pdf ` & `ai`.
- [ ] ` .doc` @ `application/msword`
- [ ] ` .docx` @ `application/vnd.openxmlformats-officedocument.wordprocessingml.document `
- [ ] `.ppt` @  `application/vnd.ms-powerpoint`
- [ ] `.pptx` @  `application/vnd.openxmlformats-officedocument.presentationml.presentation`
- [x] `.pdf` @ `application/pdf`
- [ ] `.ai`

[List of file signatures on Wikipedia](https://en.wikipedia.org/wiki/List_of_file_signatures) for inspiration

**Comment by jiro4989** [comment]
`.pdf` has already supported.

https://github.com/jiro4989/filetype#id5
